name: Android Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleRelease -PstoreFile="sign-key.jks" -PstorePassword="${{ secrets.KEY_PASSWORD }}" -PkeyAlias="key0" -PkeyPassword="${{ secrets.KEY_PASSWORD }}"
      - run: ls ./app/build/outputs/apk/release
#      - uses: actions/upload-artifact@v7
#        with:
#          name: release
#          path: ./app/build/outputs/apk/app-release.apk
#          if-no-files-found: 'error'
#          archive: 'false'
